# -*- coding: utf-8 -*-
"""PANDAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XKyRtTW3chrPJv_auVIcObrlg6dn0FS8
"""

#PANDAS

import numpy as np
import pandas as pd

path = "https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/fifa_eda.csv"

df = pd.read_csv(path)

df

df.head(3)

df[:4]

df.tail(3)

df[-3:]

df.info()

df.isna().sum()



df.isna().sum()/len(df)*100

df.drop(columns=['ID','Name'])

df.drop(columns=['ID'],inplace=True)

df.columns

#Part 2 Pandas

path = "https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/fifa_eda.csv"

df = pd.read_csv(path)

df

#PANDAS

import numpy as np
import pandas as pd

path = "https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/fifa_eda.csv"

df = pd.read_csv(path)

df

#access single column

df['Nationality']

#approach 2 using dot operator

df.Age

df.columns

#access more than 1 column [[]]

df[['Age','Club']]

df[['Age','Club']].head(4)



#to access rows and columns we have 2 more options present in pandas
#loc-label based selection
#stop is inclusive

df.loc[:3,:] #[row,column]

df.loc[:3,'Name':'Overall'] #[row,column]

df.loc[:3,'Club':'Wage'] #[row,column]

df.loc[:2,:]

#Interview Question:
df.loc[:2,['Name','Club','Nationality','Age']]

#iloc --> index based selection
#stop is exclusive
df.iloc[:2,:]

#Interview Question
#Difference between loc and iloc???

df.iloc[:2,:3]

df.iloc[:2,[10,3,1,5]]

#keep the copy of the original before making the changes
new_df=df.copy()

df.drop(columns=['Club','ID','Name'])

#check duplicate records count
print(df.duplicated().sum())

#in this dataset we dont have any duplicate record present
#but if any then we can remove them using drop_duplicates()

df.drop_duplicates()

#add a new column in existing dataframe

df['New_Name']='Rutika'
df

#add a new row in existing dataframe

import numpy as np
import pandas as pd

path = "/content/CO2 Emissions_Canada.csv"

c = pd.read_csv(path)

c

c.columns



#

c['Make'].unique()

#select only records of BMW
#c.query('expression)
c.query("Make=='BMW'")

c.query("Make=='BMW' and Cylinders>6")

c.query("Make == 'BMW' and `Engine Size(L)`>6")

c.query("`Vehicle Class`=='SUV - STANDARD' ")

c.query("`Vehicle Class`=='SUV - STANDARD' ")

#Access/Filter data using Indexing
#Boolean Indexing

c[c['Vehicle Class'] == 'FULL-SIZE']

c[c['Make'] == 'ACURA']

c[:1]

#use bitwise & operator as we have multiple True False comparison
#logical and wont work here as it is only for single comparison

c[(c['Make']=='ACURA') & (c['Cylinders']==6)]

#Groupby operations

c[:1]

c.groupby(['Make'])

list(c.groupby(['Make']))

#fetch a particular group

c.groupby(['Make']).get_group('TOYOTA')

