# -*- coding: utf-8 -*-
"""PANDAS2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XHf3dbd15fRCM-I4LIus8GZvZivWg9fL
"""

#PANDAS 2

import numpy as np
import pandas as pd

path = "/content/CO2 Emissions_Canada.csv"

c = pd.read_csv(path)

c

c.columns

c.select_dtypes(include=float)

cat_cols = ['Make', 'Model', 'Vehicle Class', 'Transmission', 'Fuel Type']

for col_name in cat_cols:
  print(col_name,':',c[col_name].nunique())



cat_cols = ['Make', 'Model', 'Vehicle Class', 'Transmission', 'Fuel Type']

for col_name in cat_cols:
  print(col_name,':',c[col_name].unique())

cat_cols = ['Make', 'Model', 'Vehicle Class', 'Transmission', 'Fuel Type']

for col_name in cat_cols:
  print(col_name,':',c[col_name].value_counts())

c['Make'].value_counts()

c['Make'].value_counts(sort=False)

print("\n\n Value Count")
cat_cols=c.select_dtypes(include='object').columns
for col_name in cat_cols:
  print(col_name,':',c[col_name].value_counts())
  print("="*30)

print("\n\n Value Count")
cat_cols=c.select_dtypes(include='object').columns
for col_name in cat_cols:
  print(col_name,':',c[col_name].value_counts().head(3))
  print("="*30)

#sort the records
c[:2]

c.describe().T

#sort the value on the basis of column name and axis
#for column axis should be 0 or 'index'
#for row axis should be 1 or 'columns'

c.sort_values(by=['CO2 Emissions(g/km)'],axis='index')

