# -*- coding: utf-8 -*-
"""Python_Modules_Exception_handling_and_Data_Science.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zFPFfCBffcNlybG-K3CMW9TuHqQ3as0b
"""

#reduce(function,iterable)

from functools import reduce
reduce (lambda x,y:x+y,[1,2,3,4,5])

k=[2,3,4,5,6]
reduce(lambda x,y:x+y,k)

#Modules in python

import math

math.e

math.pi

math.factorial(5)

#from module_name import member

from math import pi,factorial

pi

factorial(3)

from math import *

e

math.asinh(4.5)

#create a new python file like bank_info.py with below contents

name = 'gayatri'

place = 'Mumbai'

def account(name,place):
  print('Hi',name,'welcome to SBI branch',place)

from bank_info import name,place,account

name

place

account

account('Rutika','Germany')

#Exception Handling

# Exception= Error
try:
  #print(30+20) # line without error
  print(30+'P')  # line with error
except:
  print('Error occur')

for i in range(5):
  print(i)

try:
  #print(30+'P')  # line with error
  #print(30/0)
  print(30+a)
except Exception as msg:
  print('Error occur:',msg)

try:
  #print(10/4) # without exception
  print(10/0) # with exception
except Exception as msg:
  print(msg)
else:
  print('No exception do below tasks....')
finally:
  print('Zukega nai sala....')

try:
  balance = 5000
  amount = int(input('Enter amout in Rs.'))

  if  amount > balance:
    raise ValueError('Insufficient balance..')

except ValueError as e:
  print('Error:',e)

else:
  balance = balance - amount
  print('Withdrawal succesfull....')
  print('Remaining Amount is Rs. ',balance)

finally:
  print('Thank you for banking with us Visit Again.. :-)')

try:
  pin = int(input('Enter your 4 digit pin:'))
  try:
    balance = 5000
    amount = int(input('Enter amout in Rs.'))

    if  amount > balance:
      raise ValueError('Insufficient balance..')

  except ValueError as e:
    print('Error:',e)

  else:
    balance = balance - amount
    print('Withdrawal succesfull....')
    print('Remaining Amount is Rs. ',balance)

  finally:
    print('Thank you for banking with us Visit Again.. :-)')
except ValueError:
  print('Invalid PIN please enter 4 digit number ONLY')

#Data Science


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

path = "https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/CO2%20Emissions_Canada.csv"
path

#load dataset using pandas

df=pd.read_csv(path)
df

#show me rows and columns
df.shape

#show me the column names
df.columns

#show me the abstract summary of my data
df.info()

#check data type of df
df.dtypes

#access one column using dot operator

df.Model

df.Vehicle Class

#above error is becoz of space
#then use another approach of []
df['Vehicle Class']

df['Engine Size(L)']

#I need unique Vehicle classes
df['Vehicle Class'].unique()

#How many unique Vehicles classes
df['Vehicle Class'].nunique()

#now I want per category count for the Vehicle Class
df['Vehicle Class'].value_counts()

#plot a record using seaborn
sns.countplot(x='Vehicle Class',data=df)
plt.xticks(rotation=90)
plt.show()

import numpy as np

#1D
a=np.array([20,10,99,30,100])
a

np

np.__version__

a

a.max()

print(a.max())

a.min()

a.size

a.ndim

b = np.array([[10,20,1],
              [-1,5,9],
              [7,40,2]])
b

b.ndim

b.shape



np.random.random(5)

np.random.random((5,5))

np.random.random((2,2,2))

np.random

np.random.random

c=np.arange(24)
c

c.size

c.reshape((6,4))

c.reshape((8,3))

c.reshape((12,2))

c

c.shape

c.ravel()