# -*- coding: utf-8 -*-
"""Python_Datatypes_and_Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E2zGnSc5IAegr0E3jHkm8O2m3xn3eZzM
"""

a=20
type(a)

a.upper()

x = 'python'
type(x)

x=10
type(x)

id(x)

id(10)

y=10
id(y)

id('python')

p='python'
id(p)

q='python'
id(q)

e=[1,2,3]
id(e)

t=[1,2,3]
id(t)

type('.net')

type("c++")

q=[1,2,3]
type(q)

p=['X',10,22.22,'Y']
type(p)

r=['A','B','C']
type(r)

t1=(1,2,3)
t2=('A','B','C')
t3=('X',10,22.22,'Y')

type(t1)

type(t2)

type(t3)

p.append(100)
p

t1

t2=(1,2,3)
t2

id(t1),id(t2)

t4=t2
t2,t4

id(t2),id(t4)

type({})

type({12})

a={1,2,3,4}
a

b={1,3.44,'A','Python'}
b

d1={1:100,2:200,3:300}
d1

type (d1)

s='PYTHON'
s[0]

s[1]

s[-1]

len(s)//2

#Slicing
s

s[2:]

s[2:-1] #

#Access PY
s[0:2]

#Access YTH
s[1:4]

#Access HO
s[-3:-1]

#**String methods**#

s

s.lower()

s.capitalize()

'rutika shinde'.title()

'****JAVA****'.strip('*')

'  %&Python**'.strip(' %&*')

#Assignment#
p='I love my India'
p

#Access my, India, I love, ove, love my, my India
p[7:]

p[:6]

p[3:6]

p[2:9]

p[6:9]

p[9:15]

#Assignment2
#Remove space in between
p = ' J A V A '
p

p.replace('','')

"""#**List**

"""

help(list.append)

a=[]
a.append(100)
a

data = (2,3,4)
data

#add above data in a
a.append('c++')
a

#
k=[1,2,3,4,5,6,7]
k

#pop(index)  ---> we can remove element with its index
k.pop(2)

k

help(k.pop)

k

help(k.remove)

k

k.remove(5)
k

help(k.remove)

t=[1,2,3,1,4,5,1,1]
t

t.remove(1)
t

k

k.clear()
k

t

x=t.copy()
x

x.append(-1)
x

t

y=x
x

y

x.append('python')
x

y

#Tuple example
t=(10,20,30)
t

t[-1]='shridhar'
t

#Tuple packing concept
a=100
b='rutika'
c=300
a,b,c

numbs=a,b,c
numbs

d=set()
d

type(d)

#Take an input list/set/tuple/dict from the user
data= eval(input('Enter your data:'))

print(data)
print(type(data))

12.33,45,44,6,66

'vandana','snehal'

[1200]*[10]

name='rutika'

if name=='rutika':
  print('Good morning')

age=6 #int(input('Enter your age:'))
country ='india'

if age>=18 and country=='india':
  print('You are eligible for Vote')
else: #default when if condition result is False
  print('You are not eligible for Vote')

False and True

#amt=120000
amt=92000

if amt>100000:
  print('Purchase iphone')
elif amt>90000:
  print('Purchase Samsung/Vivo/RealMe phones')
elif amt>50000:
  print('Purchase Oppo/Lava...etc Phones')
else:
  print('You can try with remaining options..')

a=[10,20,30,40]
for val in a:
  print(val)

name='rutika'
for i in name:
  print(i)

#Take a dict and apply for loop

user_input={"name":"Rutika", "age":33, "city":"Bangalore"}

for key,value in user_input.items():
  print(f"Key: {key} | Value: {value}")

dict_1=dict(key1=1,key2=2)
dict_1

f={1:100,2:200}
for val in f:
  print(val)

f.items()

for val in f.items():
  print(val)

for key,val in f.items():
  print(key,val)

#ITERATIVE STATEMENTS

nms=['vandana','sarita','tauzi','prasad','pratik']

for n in nms:
  print(n)



#ITERATIVE STATEMENTS

nms=['vandana','sarita','tauzi','prasad','pratik']

for n in nms:
  print(n.upper())

#fetch names where length is <=5
for n in nms:
  if len(n)<=5:
    print(n)

nums=[23,10,70,45,90,100,35,8,16]
nums

#fetch numbers divisible by 5 and 7

for n in nums:
  if (n%5 ==0) and (n%7==0):
    print(n)



nums=[23,10,70,45,90,100,35,8,16]
nums

#fetch numbers divisible by 5 and 7

for n in nums:
  if (n%5 ==0) or (n%7==0):
    print(n)

for n in range(1,7):  #range(start,stop)
  print(n*'*')



for n in range(6,0,-1):  #range(start,stop)
  print(n*'* ')

list(range(6,0,-1))



range(6,0,-1)

for n in range(6,0,-1): #range(start,stop,step)
  print(chr(n+64))

for i in range(1,7): #1
  for j in range(i): #range(1)
    print(chr(i+64),end=' ')
  print(end='\n \n')  #new line/next line



for i in range(1,7): #1
  for j in range(i): #range(1)
    print(i)
  #print()  #new line/next line





list(range(i))

num=10
while num>5:
  print('Hello',num)
  num-=1  #num=num-1

#Sum of first 10 natural numbers
#1-10 numbers
num=1
total=0
while num<11:
  #print(num)
  total=total+num
  num+=1
print('Total sum is:',total)

#while to check the correct pin

pin=input('Enter your pin:')

while pin!='1234':
  print('Wrong pin entered')
  pin=input('Please enter correct pin')
print('Login Successful..!')

#getpass method by using import

#Guess numbers using while loop

secret=7
guess=0

while guess!=secret:
  guess=int(input('Guess the number:'))
print('Correct Guess..!!!')

6 in [7,8,10,4]



#Guess numbers using while loop

secret=[7,8,10,4]
guess=0

while guess ! in secret:
  guess=int(input('Guess the number:'))
print('Correct Guess..!!!')

#when you want to exit from the current loop then use break
f=['mango','apple','cherry','apple','grapes','mango','banana']

for item in f:
  if item == 'grapes':
    break
  else:
    print('Process:',item)

products=['mobile', 'laptop','headphone','mouse','keyboard','mobile','laptop','headphone']

search_item=input('Enter item to search:')

for item in products:
  print('Checking:',item)

  if item==search_item:
    print('Product found:',item)
    break

#continue: will help to continue the loop and skip current condition or item
products=['mobile', 'laptop','headphone','mouse','keyboard','mobile','laptop','headphone']

search_item=input('Enter item to search:')

for item in products:
  print('Checking:',item)

  if item==search_item:
    print('Product found:',item)
    continue

candidate = [
    {'name':'gayatri','status':'present'},
    {'name':'ajay','status':'absent'},
    {'name':'gorakh','status':'present'},
    {'name':'tabassum','status':'absent'},
    {'name':'ajinkya','status':'present'},
    ]
  # give an assignment to the present candidates and skip absent candidates

for student in candidate:
  if student['status'] == 'absent':
    print('Do not give assignment to:',student['name'])
    continue
  else:
    print('Give an assignment to:',student['name'])

#pass - used to create empty block.
marks = [85,0,90,76,0,70,68,-1,88,96]

for mark in marks:

  if mark == -1:
    print('Invalid marks found, Stop checking')
    break

  if mark == 0:
    print('Absent Student, Skip this student')
    continue

  if mark < 40:
    pass

  print('Valid marks:,',mark)

#List Comprehension

d=[2,3,4,5,6,7]
# create a new list with squared numbers
[num*num for num in d]

nms=['prasad','imran', 'gayatri','jay','bhavana']
[nm.title() for nm in nms]

[(nm.title(),len(nm)) for nm in nms]  #(name,len(name))

#Interview Question
#Conditional list comprehension
#fetch those names whose len is >6
#syntax:[operation for var in sequence/iteration if<condition>]
#first element fetched in nm --> check condition len(nm)>6 --> perform operation

[nm.title() for nm in nms if len(nm)>6]

#List Comprehension

#List of even numbers between 1 to 20

[num for num in range(1,21) if num%2==0]

#List of odd numbers between 1 to 20

[num for num in range(1,21) if num%2!=0]

#Ternary operator
gender=['Male','Female','Female','Male']
#convert male to 0 & female to 1

[0 if val =='Male' else 1 for val in gender]

salary = [24000,12500,45000,65000,11000,10000]
[sal +sal*0.1 if sal>25000 else sal+sal*0.2 for sal in salary]

#Explore Dict comprehension

#Example: Create a Dict {num:num^2}   for (1-10)

[{val:val*val} for val in range (1,11)]

#Function

#Function declaration

def addition():
  a=int(input('Enter first number:'))
  b=int(input('Enter second number:'))

  print('Total:',a+b)

addition()

help(len)

help(print)





def info(name,age,sal):
  print('Your name is:',name,'your age is:',age, '& your salary is:',sal  )

  info('Vandana',37,80000)

#function with return keyword

def test(balance):
  if balance <= 0:
    return 'No'
  else:
    return 'Yes'

result = test(120)

if result == 'Yes':
  print('You can perform transaction')
else:
  print('You can\'t perform transaction')

#purchase and billing example using return
items = {'rice':56,'chana':30,'wheat':60,'parle_g':10,'milk':35}
bill = []
def purchase(*args):
  for item in args:
    #print(item,items[item])
    bill.append(items[item])
  return bill

total = purchase('wheat')
print('Item amounts:',total)

from typing import AnyStr
# purchase and billing example using return
items = {'rice':56,'chana':30,'wheat':60,'parle_g':10,'milk':35}
bill = []
def purchase(*args):
  for item in args:
    #print(item,items[item])
    bill.append(items[item])
  return bill

def check(total):
  return sum(total)

# calling of purchase
total = purchase('wheat','milk')
print('Item amounts:',total)

# calling of check
ans = check(total)
print('Final bill amoutnt is Rs:',ans)

#calculate % and calculate grade
def calculate_per(marks_obtained,total_marks):
  return (marks_obtained/total_marks)*100

#print(calculate_per(450,500))

def calculate_grade(per):
  if per >= 75:
    return 'Distinction'
  elif per >= 65:
    return 'First class'
  elif per>=55:
    return 'Second class'
  elif per >= 45:
      return 'Pass class'
  else:
    return 'Fail'

per=calculate_per(420,500)
result=calculate_grade(82)
print('Total percentage is',per)
print('Your grade is',result)

a=100
b=200
a
b



a=100
b=200
print(a)
print(b)

def get_details(first_name,last_name):
  return first_name+' '+last_name

get_details('Jay','Shah')

def get_details(first_name, last_name):
  return first_name + ' ' +last_name

def welcome(name):
  return "Welcome "+ name+' to Python training'

fname = input('Enter your first name:')
lname = input('Enter your last name:')
name = get_details(fname,lname)
msg = welcome(name)
print('****',msg, '****')

#how to return multiple values:
def operation(x,y):
  add=x+y
  sub=x-y
  mul=x*y
  return add,sub


result=operation(20,10)
result

result1,result2 =operation(20,10)
result1

result2

#Lamda Function

k = [20,5,4,60,10]

# apply an operation over each element from an iterable

list(map(lambda num: num*num,k))



0x7f2839b34340

out = map(lambda num: num*num,k)
for val in out:
  print(val)

#convert below names in UPPER case using map()
names=('gayatri','abdul','snehal','jay')
tuple(map(lambda name:name.upper(),names))

p = (12,-33,40,-8,99,-12)

